apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: enforce-hook-sidecar-binding
spec:
  policyName: enforce-hook-sidecar
  validationActions: [Deny]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: enforce-vmi-hook-sidecar-binding
spec:
  policyName: enforce-vmi-hook-sidecar
  validationActions: [Deny]
