apiVersion: constraints.gatekeeper.sh/v1beta1
kind: KVMHookSidecarRequired     # Must match the 'kind' from the template
metadata:
  name: enforce-hook-sidecar
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["kubevirt.io"]
        kinds: ["VirtualMachine"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: VMIHookSidecarRequired        # MUST match ConstraintTemplate.spec.crd.spec.names.kind
metadata:
  name: enforce-vmi-hook-sidecar
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["kubevirt.io"]
        kinds: ["VirtualMachineInstance"]